### ISSUE TITLE
Header Background

### ISSUE THREAD

**Issue by akshatjain99** [akshatjain99/Kirat-Youth-Foundation#1]
First need to decide if it is going to be a photo or a video. Then while selecting either, it should fit the color scheme otherwise the header text will look bad. Photo can be done easily, but video needs to be looked at,

**Comment by akshatjain99** [comment]
Succeeded in adding header background video. Problems with height, width and responsiveness persist.

**Comment by s0rthak** [comment]
Look at this SUI module: [Embed](https://semantic-ui.com/modules/embed.html)
Also, add a solid header pehle se, I'll tell you later how to show it conditionally

**Comment by akshatjain99** [comment]
When using Embed for header background. Following issues exist: 
1. Video does not play automatically
2. Video does not span the entire page
