### ISSUE TITLE
Rows Background

### ISSUE THREAD

**Issue by akshatjain99** [akshatjain99/Kirat-Youth-Foundation#2]
Need to decide if it is going to be just colors or photos. There is one problem in both, the color/photo does not span the width of the page.

**Comment by akshatjain99** [comment]
Added row color background that span the entire width of the page. Problems with margin exist. Also need to finalize colors/images for each row.

**Comment by s0rthak** [comment]
Add random colors for now.
Open your DevTools (Ctrl + Shift + I) and have a look at which CSS property is adding a margin
(Hint: It's in the header)

**Comment by akshatjain99** [comment]
Solved, according to me. Fir bhi ek baar dekhlena.
