### ISSUE TITLE
Slant lines like Outlook

### ISSUE THREAD

**Issue by akshatjain99** [akshatjain99/Kirat-Youth-Foundation#3]
SVG is tough!

**Comment by akshatjain99** [comment]
Looked into Outlook.com and Stripe.com CSS. Looks like they have used Vector Art (google suggests Adobe Illustrator) and combined that with SVG tags in HTML to form polygons. Furthermore, they have used CSS3 transform property to rotate/translate to whatever it is they want.

**Comment by s0rthak** [comment]
Just copy and paste the svg that outlook uses for now. And then see how to change the fill color

**Comment by akshatjain99** [comment]
Added slant lines. Need to take a look at the height.
