### ISSUE TITLE
jQuery plugin for smooth scrolling

### ISSUE THREAD

**Issue by akshatjain99** [akshatjain99/Kirat-Youth-Foundation#4]
nav.js plugin just refuses to work!

**Comment by akshatjain99** [comment]
used another jQuery plugin called smoothScroll.js that fixed the scrolling issue.

**Comment by s0rthak** [comment]
This is working perfectly. Good job!
Make sure to remove the responsive-nav.css file link from index.html if you aren't using it anymore

**Comment by akshatjain99** [comment]
Yes, I have removed the responsive-nav css and js file link and also removed the master folder from the repo.
