### ISSUE TITLE
Structural Changes - 13th June, 2017

### ISSUE THREAD

**Issue by s0rthak** [akshatjain99/Kirat-Youth-Foundation#6]
1. Put each section inside a `<section>` tag
2. Inside each section, add a div with class 'grid container'.
3. Define a separate grid for each container. **Don't** define one big grid for all the sections.
4. Put individual colors to each section
5. Add SVG for slant lines between the sections
6. Implement Open Sans properly. Right now most elements still have Lato (Semantic UI default)
7. Google 'amazing landing pages' and have a look at a dozen sites. Look at which components you can use in this site for each section. Use an art file and make this layout.

**Comment by s0rthak** [comment]
Go to the Project Tab. We can track the work there.
And let's just use issues when there is something that you need my help with

**Comment by akshatjain99** [comment]
Points 1-5 done. 
Will look into 6 and 7.
